### ISSUE TITLE
Generate HTML when not provided

### ISSUE THREAD

**Issue by Robinfr** [team-gryff/react-monocle#120]
When starting Monocle without an HTML file it should generate one that references the bundle.

**Comment by jerrymao15** [comment]
this is a great idea actually! i'm assuming you wouldn't care about css from a html file if you have this option?

**Comment by jerrymao15** [comment]
@Robinfr  We've made HTML support optional now in #128 ! Thanks for the feedback

**Comment by Robinfr** [comment]
@jerrymao15 no you wouldn't. If you were using this option, you wouldn't have CSS files linked from an HTML file anyway. 

Glad to see it :+1:
