### ISSUE TITLE
add the -b and -c flags to the options

### ISSUE THREAD

**Issue by Pomax** [team-gryff/react-monocle#122]
The run instructions mention them, but it's a good idea to make the options listing complete by explicitly adding the `-b` and `-c` flags as well.

**Comment by jerrymao15** [comment]
good looks, will be adding this soon

**Comment by jerrymao15** [comment]
I've updated the Readme to include the two options (HTML is no longer required now as well per user feedback). If you have addition feedback let us know.

**Comment by Pomax** [comment]
nice!
