### ISSUE TITLE
double slash URLs

### ISSUE THREAD

**Issue by xyc** [team-gryff/react-monocle#123]
https://github.com/team-gryff/react-monocle/blob/86566a1e2c1e9196625212ecff7dad65346c39b6/src/htmlParser.js#L22

Double slash URLs like below cannot be parsed:
```html
<link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,300&subset=latin,vietnamese" />
```

**Comment by jerrymao15** [comment]
i'll give this a look, thanks for submitting

**Comment by xyc** [comment]
Thank you! @jerrymao15

**Comment by jerrymao15** [comment]
@xyc added support in #128
